const {
  ActionRowBuilder,
  StringSelectMenuBuilder,
  ButtonBuilder,
  ButtonStyle,
  EmbedBuilder,
} = require("discord.js");
const { loadUsers, saveUsers } = require("../utils/storage");
const { loadOreDB, getOreById } = require("../utils/mining");
const { TIERS, tierMeta, tierText } = require("../utils/tiers");
const { getItem, listItems } = require("./shop");
const { describeGearItem, sumAffixes, sumMainPercents, formatPct } = require("../utils/statsView");
const elements = require("../utils/element");
const { ensureUserSkills, getSkill, listSkills, craftSkill, describeSkillShort, describeSkillLong } = require("../utils/skills");
const { recordAchievementEvent } = require("./progress");

// ==================================================
// EQUIPMENT ECONOMY + ENHANCEMENT ENGINE
// ==================================================
const ORE_CRAFT_VALUE_LT={pham:20,linh:55,hoang:120,huyen:260,dia:520,thien:950,tien:1650,than:2600};
const MAX_ENH=15;
const SUCCESS_RATE=[0.90,0.85,0.78,0.68,0.55,0.45,0.35,0.25,0.18,0.12,0.10,0.08,0.06,0.04,0.03];
function clampInt(n,min,max){const x=Number(n);if(!Number.isFinite(x))return min;const i=Math.floor(x);return typeof max==="number"?Math.max(min,Math.min(max,i)):Math.max(min,i);}
function tierOrder(t){const i=TIERS.indexOf(String(t));return i>=0?i:0;}
function fmtLT(n){return Number(n||0).toLocaleString("vi-VN");}
function oreCraftValueByTier(t){return Number(ORE_CRAFT_VALUE_LT[String(t)])||ORE_CRAFT_VALUE_LT.pham;}
function oreSellValueByTier(t){return Math.max(1,Math.floor(oreCraftValueByTier(t)*0.60));}
function gearCraftValue(g){const v=Number(g?.craftValueLt);if(Number.isFinite(v)&&v>0)return Math.floor(v);const base=oreCraftValueByTier(g?.tier||"pham")*5,aff=Array.isArray(g?.affixes)?g.affixes.length:0;return Math.max(1,Math.floor(base*(1+Math.min(0.25,aff*0.05))));}
function gearSellValue(g){return Math.max(1,Math.floor(gearCraftValue(g)*0.50));}
function ensureEnhanceFields(g){if(!g||typeof g!=="object")return;g.enhanceLevel=clampInt(g.enhanceLevel,0,MAX_ENH);if(typeof g.craftValueLt!=="undefined"){const v=Number(g.craftValueLt);if(!Number.isFinite(v)||v<=0)delete g.craftValueLt;else g.craftValueLt=Math.floor(v);}}
function successRate(lv){lv=clampInt(lv,0,MAX_ENH);return lv>=MAX_ENH?0:(SUCCESS_RATE[lv]??0.1);}
function enhanceCost(g){const tier=String(g?.tier||"pham"),lv=clampInt(g?.enhanceLevel,0,MAX_ENH),base=oreSellValueByTier(tier)*8,extra=lv>10?(lv-10)*0.35:0;return{lt:Math.max(50,Math.floor(base*(1+lv*0.55+extra))),materialNeed:1+Math.floor(lv/2)+(lv>=12?1:0),minTier:tier};}
function listEnhanceMaterials(){return Object.entries(listItems()).filter(([,it])=>it?.type==="enhance_material").map(([id,it])=>({id,...it})).sort((a,b)=>tierOrder(a.tier)-tierOrder(b.tier));}
function pickMaterials(user,minTier,need){const inv=user?.inventory||{},entries=listEnhanceMaterials().map((it)=>({id:it.id,qty:Math.max(0,Number(inv[it.id])||0),item:it})).filter((x)=>x.qty>0&&tierOrder(x.item.tier)>=tierOrder(minTier)).sort((a,b)=>tierOrder(a.item.tier)-tierOrder(b.item.tier));const out=[];let left=Math.max(0,Math.floor(Number(need)||0));for(const x of entries){const take=Math.min(left,x.qty);for(let i=0;i<take;i++)out.push(x.id);left-=take;if(left<=0)break;}return left>0?[]:out;}
function attemptEnhance({user,gear}){
  if(!user||!gear)return{ok:false,message:"Dữ liệu pháp bảo chưa sẵn sàng."};ensureEnhanceFields(gear);const lv=gear.enhanceLevel;if(lv>=MAX_ENH)return{ok:false,message:"Trang bị đã đạt cấp cường hoá tối đa."};
  user.inventory=user.inventory||{};const cost=enhanceCost(gear);if((Number(user.lt)||0)<cost.lt)return{ok:false,message:`Không đủ LT (cần ${cost.lt}).`};const picked=pickMaterials(user,cost.minTier,cost.materialNeed);if(!picked.length)return{ok:false,message:`Không đủ linh tài cường hoá (cần ${cost.materialNeed} món ${tierText(cost.minTier)} trở lên).`};
  user.lt-=cost.lt;for(const id of picked){const q=Math.max(0,Number(user.inventory[id])||0)-1;if(q>0)user.inventory[id]=q;else delete user.inventory[id];}
  const rate=successRate(lv),success=Math.random()<rate,after=success?Math.min(MAX_ENH,lv+1):Math.max(0,lv-1);gear.enhanceLevel=after;return{ok:true,success,before:lv,after,rate,cost,consumedItemIds:picked};
}

function ensureMining(user){user.mining=user.mining||{};if(!Array.isArray(user.mining.tools))user.mining.tools=[];if(typeof user.mining.activeToolId==="undefined")user.mining.activeToolId=null;if(!Number.isFinite(user.mining.lastMineAt))user.mining.lastMineAt=0;if(!user.mining.ores||typeof user.mining.ores!=="object")user.mining.ores={};}
function ensureGear(user){user.gear=user.gear||{};user.gear.equipped=user.gear.equipped&&typeof user.gear.equipped==="object"?user.gear.equipped:{weapon:null,armor:null,boots:null,bracelet:null};for(const s of ["weapon","armor","boots","bracelet"])if(typeof user.gear.equipped[s]==="undefined")user.gear.equipped[s]=null;if(!Array.isArray(user.gear.bag))user.gear.bag=[];}
function ensureGearIds(user){for(const it of user.gear.bag)if(it&&!it.gid)it.gid=`g_${Date.now()}_${Math.random().toString(16).slice(2,8)}`;for(const [s,it] of Object.entries(user.gear.equipped))if(it&&!it.gid)it.gid=`g_${s}_${Date.now()}_${Math.random().toString(16).slice(2,8)}`;}
function slotLabel(s){return({weapon:"Vũ khí",armor:"Giáp",boots:"Giày",bracelet:"Vòng tay"})[s]||s;}
function short100(s){const x=String(s||"").replace(/\s+/g," ").trim();return x.length<=100?x:`${x.slice(0,97)}…`;}

async function openTools(msg){
  const users=loadUsers(),u=users[msg.author.id];ensureMining(u);if(!u.mining.tools.length)return msg.reply("🧰 Túi khoáng cụ trống. Hãy vào `-shop` để mua.");if(!u.mining.tools.some((x)=>x.iid===u.mining.activeToolId))u.mining.activeToolId=u.mining.tools[0].iid;users[msg.author.id]=u;saveUsers(users);
  const nonce=Date.now(),options=u.mining.tools.slice(0,25).map((t)=>({label:`${t.iid===u.mining.activeToolId?"[Đang dùng] ":""}${t.name||"Khoáng cụ"}`.slice(0,100),value:t.iid,description:`Độ bền ${Number(t.durability)||0}/${Number(t.durabilityMax)||0} • Hiếm +${Number(t.bonusRare)||0}%`.slice(0,100)}));
  const embed=new EmbedBuilder().setTitle("🧰 Khoáng Cụ").setColor(0x95A5A6).setDescription("Chọn khoáng cụ sẽ dùng cho lần khai khoáng kế tiếp.");const sent=await msg.reply({embeds:[embed],components:[new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`bag_tool_${msg.author.id}_${nonce}`).setPlaceholder("Chọn khoáng cụ...").addOptions(options))]});const col=sent.createMessageComponentCollector({time:90_000});
  col.on("collect",async(i)=>{if(i.user.id!==msg.author.id)return i.reply({content:"❌ Đây không phải hành trang của đạo hữu.",ephemeral:true});if(!i.isStringSelectMenu())return;await i.deferUpdate();const all=loadUsers(),cur=all[msg.author.id];ensureMining(cur);if(cur.mining.tools.some((x)=>x.iid===i.values[0]))cur.mining.activeToolId=i.values[0];all[msg.author.id]=cur;saveUsers(all);const active=cur.mining.tools.find((x)=>x.iid===cur.mining.activeToolId);return sent.edit({embeds:[EmbedBuilder.from(embed).setDescription(`Đang dùng: **${active?.name||"Khoáng cụ"}**`)]}).catch(()=>{});});col.on("end",()=>sent.edit({components:[]}).catch(()=>{}));
}

async function openOres(msg){
  let all=loadUsers(),u=all[msg.author.id];ensureMining(u);loadOreDB();const list=()=>Object.entries(u.mining.ores||{}).filter(([,q])=>Number(q)>0).map(([id,q])=>({...getOreById(id)||{id,name:id,tier:"pham"},qty:Number(q)||0})).sort((a,b)=>tierOrder(b.tier)-tierOrder(a.tier)||String(a.name).localeCompare(String(b.name),"vi"));if(!list().length)return msg.reply("🪨 Túi khoáng thạch trống. Dùng `-dao` để khai khoáng.");
  const nonce=Date.now();let selected=null;const build=()=>{const ores=list(),cur=selected?ores.find((x)=>x.id===selected):null,embed=new EmbedBuilder().setTitle("🪨 Khoáng Thạch").setColor(cur?tierMeta(cur.tier).color:0x3498DB).setDescription(cur?`${tierMeta(cur.tier).icon} **${cur.name}** • ${tierText(cur.tier)}\nĐang có: **${cur.qty}**\nGiá bán: **${fmtLT(oreSellValueByTier(cur.tier))} LT/viên**`:ores.slice(0,20).map((o)=>`${tierMeta(o.tier).icon} **${o.name}** x${o.qty} • ${tierText(o.tier)}`).join("\n")),menu=new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`bag_ore_${msg.author.id}_${nonce}`).setPlaceholder("Chọn khoáng để bán...").addOptions(ores.slice(0,25).map((o)=>({label:`${o.name} x${o.qty}`.slice(0,100),value:o.id,description:`${tierText(o.tier)} • ${fmtLT(oreSellValueByTier(o.tier))} LT/viên`.slice(0,100)}))),rows=[menu];if(cur)rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`bag_ore_sell_${nonce}_1`).setLabel("Bán 1").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`bag_ore_sell_${nonce}_5`).setLabel("Bán 5").setStyle(ButtonStyle.Primary).setDisabled(cur.qty<5),new ButtonBuilder().setCustomId(`bag_ore_sell_${nonce}_all`).setLabel(`Bán hết (${cur.qty})`).setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`bag_ore_close_${nonce}`).setLabel("Đóng").setStyle(ButtonStyle.Secondary)));return{embeds:[embed],components:rows};};
  const sent=await msg.reply(build()),col=sent.createMessageComponentCollector({time:120_000});col.on("collect",async(i)=>{if(i.user.id!==msg.author.id)return i.reply({content:"❌ Đây không phải hành trang của đạo hữu.",ephemeral:true});await i.deferUpdate();if(i.isStringSelectMenu()){selected=i.values[0];return sent.edit(build()).catch(()=>{});}if(i.customId===`bag_ore_close_${nonce}`){col.stop();return sent.edit({components:[]}).catch(()=>{});}if(!i.customId.startsWith(`bag_ore_sell_${nonce}_`)||!selected)return;all=loadUsers();u=all[msg.author.id];ensureMining(u);const ore=getOreById(selected)||{id:selected,name:selected,tier:"pham"},have=Math.max(0,Number(u.mining.ores[selected])||0),tail=i.customId.slice(`bag_ore_sell_${nonce}_`.length),qty=tail==="all"?have:Math.min(have,clampInt(tail,1,999999));if(qty<=0){selected=null;return sent.edit(build()).catch(()=>{});}const total=qty*oreSellValueByTier(ore.tier),left=have-qty;if(left>0)u.mining.ores[selected]=left;else delete u.mining.ores[selected];u.lt=(Number(u.lt)||0)+total;const titles=recordAchievementEvent(u,"sell_ore",qty)||[];all[msg.author.id]=u;saveUsers(all);if(!u.mining.ores[selected])selected=null;await i.followUp({content:`✅ Bán **${ore.name}** x${qty} → **+${fmtLT(total)} LT**.${titles.length?`\n🎖 ${titles.join(", ")}`:""}`,ephemeral:true});return sent.edit(build()).catch(()=>{});});col.on("end",()=>sent.edit({components:[]}).catch(()=>{}));
}

function gearSummary(u){const eq=u.gear.equipped||{},main=sumMainPercents(eq),aff=sumAffixes(eq),lines=Object.entries(eq).map(([s,it])=>`• **${slotLabel(s)}:** ${describeGearItem(it)}`);return new EmbedBuilder().setTitle("🛡️ Trang Bị").setColor(0x9B59B6).setDescription(`${lines.join("\n")}\n\nCông +${formatPct(main.atk)}% • Thủ +${formatPct(main.def)}% • Tốc +${formatPct(main.spd)}% • HP +${formatPct(main.hp)}% • MP +${formatPct(main.mp)}%\nPhụ tố cộng dồn: **${Object.keys(aff).length}** loại`);}
async function openGear(msg){
  let all=loadUsers(),u=all[msg.author.id];ensureGear(u);ensureGearIds(u);all[msg.author.id]=u;saveUsers(all);const nonce=Date.now();let selected=null;
  const options=()=>{const out=[];for(const [s,it] of Object.entries(u.gear.equipped))if(it)out.push({label:`[Đang mặc] ${slotLabel(s)}: ${it.name||"Trang bị"}`.slice(0,100),value:`E:${s}`});for(const it of u.gear.bag)if(it&&out.length<25)out.push({label:`[Túi] ${slotLabel(it.slot)}: ${it.name||"Trang bị"}`.slice(0,100),value:`B:${it.gid}`});return out;};
  const resolve=()=>!selected?null:selected.kind==="E"?u.gear.equipped[selected.id]||null:u.gear.bag.find((x)=>x?.gid===selected.id)||null;
  const build=()=>{const opts=options(),gear=resolve();let embed=gearSummary(u);if(gear){ensureEnhanceFields(gear);const cost=enhanceCost(gear),m=tierMeta(gear.tier||"pham");embed=new EmbedBuilder().setTitle(`${m.icon} ${gear.name||"Trang bị"} +${gear.enhanceLevel||0}`).setColor(m.color).setDescription(`${selected.kind==="E"?"Đang mặc":"Trong túi"} • **${slotLabel(gear.slot||selected.id)}**\nPhẩm: **${tierText(gear.tier||"pham")}**\nCường hóa kế: **${Math.round(successRate(gear.enhanceLevel)*100)}%** • ${fmtLT(cost.lt)} LT + ${cost.materialNeed} linh tài${selected.kind==="B"?`\nGiá bán: **${fmtLT(gearSellValue(gear))} LT**`:""}`);}const rows=[];if(opts.length)rows.push(new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`bag_gear_${msg.author.id}_${nonce}`).setPlaceholder("Chọn trang bị...").addOptions(opts)));if(gear){const row=new ActionRowBuilder();row.addComponents(selected.kind==="B"?new ButtonBuilder().setCustomId(`bag_gear_equip_${nonce}`).setLabel("Mặc").setStyle(ButtonStyle.Success):new ButtonBuilder().setCustomId(`bag_gear_unequip_${nonce}`).setLabel("Tháo").setStyle(ButtonStyle.Secondary));row.addComponents(new ButtonBuilder().setCustomId(`bag_gear_enh_${nonce}`).setLabel("Cường hóa").setStyle(ButtonStyle.Primary));if(selected.kind==="B")row.addComponents(new ButtonBuilder().setCustomId(`bag_gear_sell_${nonce}`).setLabel("Bán").setStyle(ButtonStyle.Danger));row.addComponents(new ButtonBuilder().setCustomId(`bag_gear_close_${nonce}`).setLabel("Đóng").setStyle(ButtonStyle.Secondary));rows.push(row);}return{embeds:[embed],components:rows};};
  const sent=await msg.reply(build()),col=sent.createMessageComponentCollector({time:120_000});col.on("collect",async(i)=>{if(i.user.id!==msg.author.id)return i.reply({content:"❌ Đây không phải hành trang của đạo hữu.",ephemeral:true});await i.deferUpdate();if(i.isStringSelectMenu()){const [kind,id]=i.values[0].split(":");selected={kind,id};return sent.edit(build()).catch(()=>{});}if(i.customId===`bag_gear_close_${nonce}`){col.stop();return sent.edit({components:[]}).catch(()=>{});}all=loadUsers();u=all[msg.author.id];ensureGear(u);let gear=selected?.kind==="E"?u.gear.equipped[selected.id]:u.gear.bag.find((x)=>x?.gid===selected?.id);if(!gear){selected=null;return sent.edit(build()).catch(()=>{});}if(i.customId===`bag_gear_equip_${nonce}`&&selected.kind==="B"){const idx=u.gear.bag.findIndex((x)=>x?.gid===selected.id),slot=gear.slot;if(u.gear.equipped[slot])u.gear.bag.push(u.gear.equipped[slot]);u.gear.equipped[slot]=gear;u.gear.bag.splice(idx,1);selected={kind:"E",id:slot};}else if(i.customId===`bag_gear_unequip_${nonce}`&&selected.kind==="E"){u.gear.equipped[selected.id]=null;u.gear.bag.push(gear);selected=null;}else if(i.customId===`bag_gear_sell_${nonce}`&&selected.kind==="B"){const idx=u.gear.bag.findIndex((x)=>x?.gid===selected.id),price=gearSellValue(gear);u.gear.bag.splice(idx,1);u.lt=(Number(u.lt)||0)+price;const titles=recordAchievementEvent(u,"sell_gear",1)||[];await i.followUp({content:`✅ Bán **${gear.name||"Trang bị"}** → **+${fmtLT(price)} LT**.${titles.length?`\n🎖 ${titles.join(", ")}`:""}`,ephemeral:true});selected=null;}else if(i.customId===`bag_gear_enh_${nonce}`){const res=attemptEnhance({user:u,gear});if(!res.ok)return i.followUp({content:`❌ ${res.message}`,ephemeral:true});let titles=[];if(res.after>=5)titles.push(...recordAchievementEvent(u,"enh_plus5",1));if(res.after>=10)titles.push(...recordAchievementEvent(u,"enh_plus10",1));if(res.after>=15)titles.push(...recordAchievementEvent(u,"enh_plus15",1));if(!res.success)titles.push(...recordAchievementEvent(u,"enh_fail",1));await i.followUp({content:`${res.success?"✅ Thành công":"❌ Thất bại"}: **+${res.before} → +${res.after}**${titles.length?`\n🎖 ${[...new Set(titles)].join(", ")}`:""}`,ephemeral:true});}all[msg.author.id]=u;saveUsers(all);return sent.edit(build()).catch(()=>{});});col.on("end",()=>sent.edit({components:[]}).catch(()=>{}));
}

function skillsEmbed(u){ensureUserSkills(u);const eq=u.skills.equipped,el=u.element||"kim",act=eq.actives.map((id,i)=>`${i+1}. ${id?`**${getSkill(id)?.name||id}**`:"_(trống)_"}`).join("\n"),pass=eq.passive?`**${getSkill(eq.passive)?.name||eq.passive}**`:"_(trống)_",shards=u.skills.shards[el]||{rare:0,epic:0};return new EmbedBuilder().setTitle("📜 Bí Kíp").setColor(0x8E44AD).setDescription(`Hệ: ${elements.display[el]||el}\n\n**Chủ động**\n${act}\n**Bị động:** ${pass}\n\nMảnh Hiếm: **${shards.rare||0}** • Cực hiếm: **${shards.epic||0}**`);}
async function openSkills(msg){
  let all=loadUsers(),u=all[msg.author.id];ensureUserSkills(u);all[msg.author.id]=u;saveUsers(all);const nonce=Date.now();let mode="main",slot=null,picked=null,rarity=null;
  const build=()=>{const rows=[],embed=skillsEmbed(u);if(mode==="main")rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`bag_sk_equip_${nonce}`).setLabel("Trang bị").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`bag_sk_rare_${nonce}`).setLabel("Ghép Hiếm").setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`bag_sk_epic_${nonce}`).setLabel("Ghép Cực hiếm").setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`bag_sk_close_${nonce}`).setLabel("Đóng").setStyle(ButtonStyle.Secondary)));if(mode==="equip"){rows.push(new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`bag_sk_slot_${nonce}`).setPlaceholder("Chọn slot...").addOptions({label:"Chủ động 1",value:"a1"},{label:"Chủ động 2",value:"a2"},{label:"Chủ động 3",value:"a3"},{label:"Chủ động 4",value:"a4"},{label:"Bị động",value:"passive"})));if(slot){const want=slot==="passive"?"passive":"active",pool=(u.skills.owned||[]).map((id)=>({id,s:getSkill(id)})).filter((x)=>x.s?.kind===want&&(!x.s.element||x.s.element===u.element));if(pool.length)rows.push(new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`bag_sk_pick_${nonce}`).setPlaceholder("Chọn bí kíp...").addOptions(pool.slice(0,25).map((x)=>({label:x.s.name.slice(0,100),value:x.id,description:short100(describeSkillShort(x.s))})))));}rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`bag_sk_apply_${nonce}`).setLabel("Áp dụng").setStyle(ButtonStyle.Success).setDisabled(!slot||!picked),new ButtonBuilder().setCustomId(`bag_sk_remove_${nonce}`).setLabel("Tháo").setStyle(ButtonStyle.Danger).setDisabled(!slot),new ButtonBuilder().setCustomId(`bag_sk_back_${nonce}`).setLabel("Quay lại").setStyle(ButtonStyle.Secondary)));}if(mode==="craft"){const pool=listSkills({element:u.element,rarity}).filter((s)=>!(u.skills.owned||[]).includes(s.id));if(pool.length)rows.push(new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`bag_sk_craftpick_${nonce}`).setPlaceholder("Chọn bí kíp để ghép...").addOptions(pool.slice(0,25).map((s)=>({label:s.name.slice(0,100),value:s.id,description:short100(describeSkillShort(s))}))));rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`bag_sk_craft_${nonce}`).setLabel("Ghép").setStyle(ButtonStyle.Success).setDisabled(!picked),new ButtonBuilder().setCustomId(`bag_sk_back_${nonce}`).setLabel("Quay lại").setStyle(ButtonStyle.Secondary)));if(picked){const sk=getSkill(picked);if(sk)embed.addFields({name:sk.name,value:describeSkillLong(sk).slice(0,1024)});}}return{embeds:[embed],components:rows};};
  const sent=await msg.reply(build()),col=sent.createMessageComponentCollector({time:150_000});col.on("collect",async(i)=>{if(i.user.id!==msg.author.id)return i.reply({content:"❌ Đây không phải hành trang của đạo hữu.",ephemeral:true});await i.deferUpdate();const cid=i.customId;if(cid===`bag_sk_close_${nonce}`){col.stop();return sent.edit({components:[]}).catch(()=>{});}if(cid===`bag_sk_back_${nonce}`){mode="main";slot=null;picked=null;rarity=null;return sent.edit(build()).catch(()=>{});}if(cid===`bag_sk_equip_${nonce}`){mode="equip";slot=null;picked=null;return sent.edit(build()).catch(()=>{});}if(cid===`bag_sk_rare_${nonce}`||cid===`bag_sk_epic_${nonce}`){mode="craft";rarity=cid.includes("epic")?"epic":"rare";picked=null;return sent.edit(build()).catch(()=>{});}if(i.isStringSelectMenu()&&cid===`bag_sk_slot_${nonce}`){slot=i.values[0];picked=null;return sent.edit(build()).catch(()=>{});}if(i.isStringSelectMenu()&&(cid===`bag_sk_pick_${nonce}`||cid===`bag_sk_craftpick_${nonce}`)){picked=i.values[0];return sent.edit(build()).catch(()=>{});}all=loadUsers();u=all[msg.author.id];ensureUserSkills(u);if(cid===`bag_sk_apply_${nonce}`&&slot&&picked){if(slot==="passive")u.skills.equipped.passive=picked;else u.skills.equipped.actives[Math.max(0,Math.min(3,Number(slot.slice(1))-1))]=picked;}else if(cid===`bag_sk_remove_${nonce}`&&slot){if(slot==="passive")u.skills.equipped.passive=null;else u.skills.equipped.actives[Math.max(0,Math.min(3,Number(slot.slice(1))-1))]=null;picked=null;}else if(cid===`bag_sk_craft_${nonce}`&&picked){const res=craftSkill(u,picked);if(!res.ok)return i.followUp({content:res.message,ephemeral:true});await i.followUp({content:`✅ ${res.message}`,ephemeral:true});mode="main";picked=null;rarity=null;}all[msg.author.id]=u;saveUsers(all);return sent.edit(build()).catch(()=>{});});col.on("end",()=>sent.edit({components:[]}).catch(()=>{}));
}

async function openItems(msg){const u=loadUsers()[msg.author.id],inv=u.inventory||{},rows=Object.entries(inv).filter(([,q])=>Number(q)>0).map(([id,q])=>{const it=getItem(id);return{order:it?.tier?tierOrder(it.tier):-1,text:`• ${it?.emoji||""} **${it?.name||id}** x${q}${it?.tier?` • ${tierText(it.tier)}`:""}`};}).sort((a,b)=>a.order-b.order).slice(0,40);return msg.reply({embeds:[new EmbedBuilder().setTitle("📦 Vật Phẩm").setColor(0x95A5A6).setDescription(rows.length?rows.map((x)=>x.text).join("\n"):"(Trống)")]});}

const bagCommand={
  name:"bag",aliases:["tui"],description:"Túi: khoáng cụ, khoáng, bí kíp, trang bị và vật phẩm.",
  run:async(_client,msg)=>{const users=loadUsers(),u=users[msg.author.id];if(!u)return msg.reply("❌ Đạo hữu chưa nhập đạo. Dùng `-create` trước.");ensureMining(u);ensureGear(u);ensureUserSkills(u);ensureGearIds(u);users[msg.author.id]=u;saveUsers(users);const nonce=Date.now(),embed=new EmbedBuilder().setTitle("🎒 Túi").setColor(0x5865F2).setDescription(`Cảnh giới: **${u.realm||"(chưa rõ)"}**\nChọn khu vực cần mở.`),row=new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`bag_cat_${msg.author.id}_${nonce}`).setPlaceholder("Chọn mục...").addOptions({label:"🧰 Khoáng cụ",value:"tools"},{label:"🪨 Khoáng thạch",value:"ores"},{label:"📜 Bí kíp",value:"skills"},{label:"🛡️ Trang bị",value:"gear"},{label:"📦 Vật phẩm",value:"items"})),sent=await msg.reply({embeds:[embed],components:[row]}),col=sent.createMessageComponentCollector({time:60_000});col.on("collect",async(i)=>{if(i.user.id!==msg.author.id)return i.reply({content:"❌ Đây không phải hành trang của đạo hữu.",ephemeral:true});if(!i.isStringSelectMenu())return;await i.deferUpdate();await sent.edit({components:[]}).catch(()=>{});col.stop();const v=i.values[0];if(v==="tools")return openTools(msg);if(v==="ores")return openOres(msg);if(v==="skills")return openSkills(msg);if(v==="gear")return openGear(msg);return openItems(msg);});}
};

module.exports={commands:[bagCommand],ORE_CRAFT_VALUE_LT,clampInt,tierOrder,fmtLT,oreCraftValueByTier,oreSellValueByTier,gearCraftValue,gearSellValue,ensureEnhanceFields,successRate,enhanceCost,attemptEnhance};
